export enum Env {
  DB_PORT = 'DATABASE_PORT',
  DB_DATABASE = 'DATABASE_DATABASE',
  DB_URL = 'DATABASE_URL',
  DB_HOST = 'DATABASE_HOST',

  DB_USERNAME = 'DATABASE_USERNAME',
  DB_PASSWORD = 'DATABASE_PASSWORD',

  JWT_SECRET = 'JWT_SECRET',

  EMAIL_USER = 'EMAIL_USER',
  EMAIL_CLIENT_ID = 'EMAIL_CLIENT_ID',
  EMAIL_CLIENT_SECRET = 'EMAIL_CLIENT_SECRET',
  EMAIL_REFRESH_TOKEN = 'EMAIL_REFRESH_TOKEN',

  IMGBB_API_KEY = 'IMGBB_API_KEY',
  MESSAGE_ENCRYPTION_KEY = 'MESSAGE_ENCRYPTION_KEY',
}
